# Semantic Technology

Sources:
- https://wikipedia2vec.github.io/wikipedia2vec/usage/
- https://radimrehurek.com/gensim/search.html?q=learn+from+websites&check_keywords=yes&area=default
- https://pypi.org/project/wikipedia2vec/1.0.5/
- https://datascience.stackexchange.com/questions/49431/how-to-train-an-existing-word2vec-gensim-model-on-new-words


Training Sources:
- https://qz.com/2142992/transcript-of-volodymyr-zelenskyys-speech-to-the-us-congress/
- https://kyivindependent.com/national/zelenskys-full-speech-at-munich-security-conference/
- https://www.timesofisrael.com/full-text-ukraine-president-zelenskys-speech-to-israeli-lawmakers/
- https://www.theguardian.com/world/2022/mar/08/thirteen-days-of-struggle-volodymyr-zelenskiys-speech-to-uk-parliament-transcript
- https://edition.cnn.com/2022/03/24/politics/zelensky-speech-nato-transcript/index.html

In [144]:
pip install html2text

You should consider upgrading via the 'g:\python\python.exe -m pip install --upgrade pip' command.


In [145]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'g:\python\python.exe -m pip install --upgrade pip' command.


In [146]:
pip install wikipedia2vec

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'g:\python\python.exe -m pip install --upgrade pip' command.


In [147]:
pip install gensim


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'g:\python\python.exe -m pip install --upgrade pip' command.


In [148]:
from wikipedia2vec import Wikipedia2Vec
from gensim.test.utils import datapath
from gensim.models import KeyedVectors

MODEL_PATH = "enwiki_20180420_100d.txt"

# Takes 11m 32.5s
wv_from_text = KeyedVectors.load_word2vec_format((MODEL_PATH), binary=False)


In [149]:
wv_from_text.most_similar(positive=['ukraine'])

[('ENTITY/Ukraine', 0.8916355967521667),
 ('belarus', 0.888225257396698),
 ('rivne', 0.8229362964630127),
 ('ternopil', 0.8213138580322266),
 ('vinnytsia', 0.8198360800743103),
 ('kharkiv', 0.8192664980888367),
 ('lviv', 0.8175711035728455),
 ('russia', 0.8113815188407898),
 ('frankivsk', 0.8110743761062622),
 ('ukrainian', 0.8106153607368469)]

In [150]:
wv_from_text.most_similar(positive=['russia'])

[('ukraine', 0.8113813996315002),
 ('ENTITY/Russia', 0.8110665082931519),
 ('kazakhstan', 0.802672803401947),
 ('belarus', 0.800453245639801),
 ('yekaterinburg', 0.7816581130027771),
 ('tartarstan', 0.7815535664558411),
 ('moscow', 0.7720255255699158),
 ('15471584', 0.7660513520240784),
 ('kaliningrad', 0.7582147717475891),
 ('urals', 0.7565478682518005)]

In [151]:
wv_from_text.most_similar(positive=['sanction'])

[('sanctioned', 0.7369568943977356),
 ('sanctioning', 0.7306732535362244),
 ('sanctions', 0.718333899974823),
 ('revoking', 0.7159944772720337),
 ('revoke', 0.715387225151062),
 ('rescind', 0.7072172164916992),
 ('stipulations', 0.6976112127304077),
 ('deditio', 0.6960795521736145),
 ('revoked', 0.6935349702835083),
 ('retrospectivity', 0.6914761066436768)]

In [152]:
wv_from_text.most_similar(positive=['crimea'])

[('crimean', 0.8625871539115906),
 ('ENTITY/Crimea', 0.8603824377059937),
 ('sevastopol', 0.8237816095352173),
 ('ENTITY/Autonomous_Republic_of_Crimea', 0.8013858795166016),
 ('caucasus', 0.8003067374229431),
 ('ENTITY/Sevastopol', 0.7968735694885254),
 ('abkhazia', 0.7956523299217224),
 ('aqyar', 0.7920345067977905),
 ('feodosia', 0.789340615272522),
 ('kerch', 0.7874438762664795)]

In [153]:
wv_from_text.most_similar(positive=['donbass'])

[('donbas', 0.875837504863739),
 ('ENTITY/Donbass', 0.8166588544845581),
 ('ENTITY/War_in_Donbass', 0.8134056925773621),
 ('ENTITY/Donets#Geography_and_hydrology', 0.7773705720901489),
 ('kramatorsk', 0.7690269947052002),
 ('ilovaisk', 0.7655662298202515),
 ('mariupol', 0.7652601599693298),
 ('ENTITY/Luhansk_Oblast', 0.7632381319999695),
 ('debaltsevo', 0.7609618902206421),
 ('rovenky', 0.7597677707672119)]

In [154]:
wv_from_text.most_similar(positive=['kiev'])

[('ENTITY/Kiev', 0.9116911292076111),
 ('kharkiv', 0.8846046328544617),
 ('lviv', 0.8785252571105957),
 ('kyiv', 0.8708134293556213),
 ('chernihiv', 0.863882303237915),
 ('lvov', 0.8503857254981995),
 ('kharkov', 0.8488938212394714),
 ('volodymyr', 0.8428213000297546),
 ('zhytomyr', 0.8426886200904846),
 ('poltava', 0.841640055179596)]

In [155]:
wv_from_text.most_similar(positive=['drone'])

[('drones', 0.8597627282142639),
 ('ababil', 0.7620076537132263),
 ('skyprowler', 0.7281385064125061),
 ('mechanaughts', 0.7275535464286804),
 ('ucavs', 0.7260419130325317),
 ('svbied', 0.7214287519454956),
 ('ambessence', 0.7185141444206238),
 ('3205th', 0.718436598777771),
 ('satuma', 0.7164090275764465),
 ('ENTITY/Pyros_(bomb)', 0.716185986995697)]

In [156]:
wv_from_text.most_similar(positive=['missile'])

[('missiles', 0.9134847521781921),
 ('ballistic', 0.870313286781311),
 ('icbm', 0.8484668135643005),
 ('mrbm', 0.8381847143173218),
 ('ENTITY/Ballistic_missile', 0.8278685212135315),
 ('slbm', 0.826542854309082),
 ('icbms', 0.8182637691497803),
 ('brbm', 0.8161768913269043),
 ('ENTITY/Surface-to-surface_missile', 0.8117130994796753),
 ('seasparrow', 0.8107771277427673)]

In [157]:
wv_from_text.most_similar(positive=['army'])

[('corps', 0.820118248462677),
 ('forces', 0.8026898503303528),
 ('troops', 0.7948513627052307),
 ('armies', 0.7779507637023926),
 ('expeditionary', 0.7663358449935913),
 ('brigade', 0.7611337304115295),
 ('cavalry', 0.7610782384872437),
 ('soldiers', 0.7584280967712402),
 ('military', 0.7572802901268005),
 ('hullyeondae', 0.7566160559654236)]

In [158]:
wv_from_text.most_similar(positive=['target'])

[('targets', 0.8499306440353394),
 ('targeting', 0.8013738393783569),
 ('targeted', 0.7695007920265198),
 ('druggable', 0.7485793828964233),
 ('ratscat', 0.7394058704376221),
 ('targeter', 0.7353816628456116),
 ('darkhotel', 0.7282263040542603),
 ('glsdb', 0.7280399203300476),
 ('96l6e', 0.7258893847465515),
 ('siaswfcs', 0.7199010848999023)]

# Training existing model

Training Sources:
- https://qz.com/2142992/transcript-of-volodymyr-zelenskyys-speech-to-the-us-congress/
- https://kyivindependent.com/national/zelenskys-full-speech-at-munich-security-conference/
- https://www.timesofisrael.com/full-text-ukraine-president-zelenskys-speech-to-israeli-lawmakers/
- https://www.theguardian.com/world/2022/mar/08/thirteen-days-of-struggle-volodymyr-zelenskiys-speech-to-uk-parliament-transcript
- https://edition.cnn.com/2022/03/24/politics/zelensky-speech-nato-transcript/index.html

In [159]:
from gensim.models import Word2Vec
old_model = wv_from_text
len(old_model)

4530030

Alternativ:

https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.LineSentence

https://datascience.stackexchange.com/questions/49431/how-to-train-an-existing-word2vec-gensim-model-on-new-words

Collect first data from:
https://qz.com/2142992/transcript-of-volodymyr-zelenskyys-speech-to-the-us-congress/

In [160]:
import requests
import html2text
import html
import re

sentences_source_one = []

url = 'https://qz.com/2142992/transcript-of-volodymyr-zelenskyys-speech-to-the-us-congress/'
r = requests.get(url)
content = r.text.split('<div id="article-content"><div>')
h = html2text.HTML2Text()
h.ignore_links = True
new_content = h.handle(content[1])

new_content = str(new_content).replace("\n", " ")
new_content = str(new_content).replace("_", " ")
new_content = str(new_content).replace("#", " ")
new_content = str(new_content).split("Thank you. Glory to Ukraine.")[0]
new_content = str(new_content).split(".")

for content in new_content:
    if content != " ":
        if "”" in content:
            sentences_source_one.append(content.split("”")[1].strip().split(" "))
        else:
            sentences_source_one.append(content.strip().split(" "))

for sentence in sentences_source_one:
    if len(sentence) < 2:
        sentences_source_one.remove(sentence)

with open("source_file_one.txt", "w") as resultFile:
    for sentence in sentences_source_one:
        for word in sentence:
            if word != "":
                resultFile.write(''.join(e for e in word if e.isalnum()))
                resultFile.write(" ")
        resultFile.write("\n")

resultFile.close()

In [161]:
import gensim
import numpy as np
data_source_one = gensim.models.word2vec.LineSentence('source_file_one.txt')

new_model = Word2Vec(vector_size=100, min_count=1, workers=4)
new_model.build_vocab(data_source_one)
new_model.build_vocab([list(old_model.key_to_index.keys())], update=True)

In [162]:
test_model = new_model

In [163]:
print(test_model.wv.vectors_lockf)
print(old_model.vector_size)
print(len(old_model))

[1.]
100
4530030


In [167]:
test_model.wv.vectors_lockf = np.ones(len(old_model)+100, dtype=np.float32)

In [168]:
# Reset
test_model.wv.vectors_norm = None

In [169]:
test_model.wv.intersect_word2vec_format(MODEL_PATH,lockf=1.0, binary=False)
test_model.wv.most_similar('ukraine', topn=10)

[('ENTITY/Ukraine', 0.8916355967521667),
 ('belarus', 0.888225257396698),
 ('rivne', 0.8229362964630127),
 ('ternopil', 0.8213138580322266),
 ('vinnytsia', 0.8198360800743103),
 ('kharkiv', 0.8192664980888367),
 ('lviv', 0.8175711035728455),
 ('russia', 0.8113815188407898),
 ('frankivsk', 0.8110743761062622),
 ('ukrainian', 0.8106153607368469)]

In [170]:
#new_model.build_vocab(data_source_one, update=True)
print("Break")
new_model.train(data_source_one, total_examples=len(sentences_source_one), epochs=100)


Break


(131302, 134700)

```[('ukraine', 0.8113813996315002),
 ('ENTITY/Russia', 0.8110665082931519),
 ('kazakhstan', 0.802672803401947),
 ('belarus', 0.800453245639801),
 ('yekaterinburg', 0.7816581130027771),
 ('tartarstan', 0.7815535664558411),
 ('moscow', 0.7720255255699158),
 ('15471584', 0.7660513520240784),
 ('kaliningrad', 0.7582147717475891),
 ('urals', 0.7565478682518005)]

```
array([-0.0214,  0.0182, -0.2011,  0.1701, -0.175 , -0.3055, -0.0416,
       -0.5173,  0.2423, -0.4145,  0.3219, -0.0012, -0.2268, -0.3011,
        0.1544,  0.101 ,  0.2251, -0.5355, -0.1571,  0.2717, -0.3546,
        0.9193, -0.3132, -0.1918, -0.3202, -0.1104, -0.2342,  0.0768,
        0.2848,  0.3656,  0.0302, -0.3069,  0.1712,  0.5927,  0.4725,
       -1.1371,  0.533 , -0.2878,  0.3628, -0.3056,  0.6182,  0.5567,
       -0.5227,  0.4879, -0.6435, -0.4522,  0.2326,  0.7256, -0.084 ,
       -0.3752,  0.1817,  0.7683,  0.3572, -0.1495,  0.2747,  0.4824,
        0.966 ,  0.0893, -1.0474, -0.0785,  0.1729,  0.261 , -0.0413,
        0.3138,  1.1408, -0.5658, -0.3542,  0.0951,  0.4378, -0.983 ,
       -0.1035,  0.2077,  0.0347, -0.0721,  0.0964,  0.5524, -0.218 ,
        0.0305, -0.0537, -0.4136, -0.1523, -0.1132,  0.4943, -0.7518,
        0.3106,  0.2683,  0.4516, -0.1572, -0.1039, -0.1302,  0.3041,
        0.6854,  0.3632, -0.2897,  0.3596, -0.0575, -0.1241,  0.5227,
        0.3266,  0.5276], dtype=float32)

In [ ]:
test_model.wv.get_vector("ukraine")

array([-0.0214,  0.0182, -0.2011,  0.1701, -0.175 , -0.3055, -0.0416,
       -0.5173,  0.2423, -0.4145,  0.3219, -0.0012, -0.2268, -0.3011,
        0.1544,  0.101 ,  0.2251, -0.5355, -0.1571,  0.2717, -0.3546,
        0.9193, -0.3132, -0.1918, -0.3202, -0.1104, -0.2342,  0.0768,
        0.2848,  0.3656,  0.0302, -0.3069,  0.1712,  0.5927,  0.4725,
       -1.1371,  0.533 , -0.2878,  0.3628, -0.3056,  0.6182,  0.5567,
       -0.5227,  0.4879, -0.6435, -0.4522,  0.2326,  0.7256, -0.084 ,
       -0.3752,  0.1817,  0.7683,  0.3572, -0.1495,  0.2747,  0.4824,
        0.966 ,  0.0893, -1.0474, -0.0785,  0.1729,  0.261 , -0.0413,
        0.3138,  1.1408, -0.5658, -0.3542,  0.0951,  0.4378, -0.983 ,
       -0.1035,  0.2077,  0.0347, -0.0721,  0.0964,  0.5524, -0.218 ,
        0.0305, -0.0537, -0.4136, -0.1523, -0.1132,  0.4943, -0.7518,
        0.3106,  0.2683,  0.4516, -0.1572, -0.1039, -0.1302,  0.3041,
        0.6854,  0.3632, -0.2897,  0.3596, -0.0575, -0.1241,  0.5227,
        0.3266,  0.5

In [ ]:
old_model.get_vector("ukraine")

array([-0.0214,  0.0182, -0.2011,  0.1701, -0.175 , -0.3055, -0.0416,
       -0.5173,  0.2423, -0.4145,  0.3219, -0.0012, -0.2268, -0.3011,
        0.1544,  0.101 ,  0.2251, -0.5355, -0.1571,  0.2717, -0.3546,
        0.9193, -0.3132, -0.1918, -0.3202, -0.1104, -0.2342,  0.0768,
        0.2848,  0.3656,  0.0302, -0.3069,  0.1712,  0.5927,  0.4725,
       -1.1371,  0.533 , -0.2878,  0.3628, -0.3056,  0.6182,  0.5567,
       -0.5227,  0.4879, -0.6435, -0.4522,  0.2326,  0.7256, -0.084 ,
       -0.3752,  0.1817,  0.7683,  0.3572, -0.1495,  0.2747,  0.4824,
        0.966 ,  0.0893, -1.0474, -0.0785,  0.1729,  0.261 , -0.0413,
        0.3138,  1.1408, -0.5658, -0.3542,  0.0951,  0.4378, -0.983 ,
       -0.1035,  0.2077,  0.0347, -0.0721,  0.0964,  0.5524, -0.218 ,
        0.0305, -0.0537, -0.4136, -0.1523, -0.1132,  0.4943, -0.7518,
        0.3106,  0.2683,  0.4516, -0.1572, -0.1039, -0.1302,  0.3041,
        0.6854,  0.3632, -0.2897,  0.3596, -0.0575, -0.1241,  0.5227,
        0.3266,  0.5

In [ ]:
test_model.corpus_count

106

In [ ]:
test_model.corpus_total_words

1347

In [ ]:
len(sentences_source_one)

106

In [172]:
test_model.compute_loss

False

In [ ]:
test_model.wv.most_similar('ukraine', topn=10)

[('ENTITY/Ukraine', 0.8916355967521667),
 ('belarus', 0.888225257396698),
 ('rivne', 0.8229362964630127),
 ('ternopil', 0.8213138580322266),
 ('vinnytsia', 0.8198360800743103),
 ('kharkiv', 0.8192664980888367),
 ('lviv', 0.8175711035728455),
 ('russia', 0.8113815188407898),
 ('frankivsk', 0.8110743761062622),
 ('ukrainian', 0.8106153607368469)]